blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('create/', views.post_create, name='post_create'),
    path('(<id>\d+)/<slug>[\w-]+/', views.post_detail, name='post_detail'),
    path('<slug>[\w-]+/edit/', views.post_update, name='update'),
    path('<slug>[\w-]+/delete/', views.post_delete, name='post_delete'),

]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_list, name='home'),
    path('category_chart/', views.category_chart, name='category_chart'),
    path('shops/', views.shop_list, name='shop_list'),
    path('shops/<int:shop_id>/', views.shop_detail, name='shop_detail'),
    path('ads_list', views.ads_list, name='ads_list'),
    path('allads_list', views.allads_list, name='allads_list'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('analytics/customer/', views.customer_analytics, name='customer_analytics'),
    path('analytics/dispatcher/', views.dispatcher_analytics, name='dispatcher_analytics'),
    path('analytics/shop/', views.shop_analytics, name='shop_analytics'),
    path('nearby_shops/', views.nearby_shops, name='nearby_shops'),
    path('favourites/', views.ads_favourite_list, name="favourites"),
    path('favourite_ads/', views.favourite_ads, name="favourite_ads"),
    path(
        "wishlist/<int:item_id>/preferences/",
        views.update_wishlist_preferences,
        name="wishlist_preferences",
    ),
    path("shops/<int:shop_id>/subscribe/", views.toggle_shop_subscription, name="toggle_shop_subscription"),
    path("shop-notifications/", views.shop_notifications, name="shop_notifications"),
    path('products/<int:id>/<slug:slug>/preview/', views.ad_preview, name='ad_preview'),
    path('<slug:category_slug>/', views.ads_list, name='ads_list_by_category'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('<int:id>/favourite_ad/',views.favourite_ad, name='favourite_ad'),
    path('<int:id>/favourite_delete/',views.favourite_delete, name='favourite_delete'),
    path('<int:id>/<slug:slug>/', views.ad_detail, name='ad_detail'),
    path('category_count/',views.category_count,name='category_count'),
    path("submit_review/<int:post_id>/", views.submit_review, name="submit_review"),

]

seafood/urls.py
import importlib.util
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='api-schema'), name='api-docs'),
    path('api/v1/', include('seafood.api_urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('foodcreate/',include('foodCreate.urls', namespace='foodcreate')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('marketing/',include('marketing.urls', namespace='marketing')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('budget/', include('budget.urls', namespace='budget')),
    path('order/',include('order.urls', namespace='order')),
    path('owner/',include('owner.urls', namespace='owner')),
    path('voice/', include('voice.urls', namespace='voice')),
    path('',include('home.urls', namespace='home')),
    path('product_search/',include('search.urls', namespace='product_search')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path("paystack/", include(('django_paystack.urls','paystack'),namespace='paystack')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/api/urls.py
from django.urls import path

from .views import RecommendationsAPIView, SearchAPIView

urlpatterns = [
    path('', SearchAPIView.as_view(), name='api-search'),
    path('recommendations/', RecommendationsAPIView.as_view(), name='api-recommendations'),
]

search/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'search'

urlpatterns = [
    path('product_filter/',views.filter,name='product_filter'),
    path('recommendations/', views.product_recommendations, name='recommendations'),
#    path('ajax_filter/',views.ajax_filter,name='ajax_filter'),

]

search/models.py
from django.db import models

# Create your models here.

search/api/views.py
from rest_framework import permissions
from rest_framework import serializers
from rest_framework.views import APIView

from rest_framework.response import Response

from foodCreate.serializers import ProductsSerializer
from search.recommendations import get_recommended_products
from search.serializers import SearchQuerySerializer
from search.services import filter_products
from drf_spectacular.utils import extend_schema


class APIPayloadSerializer(serializers.Serializer):
    pass


class BaseAPIView(APIView):
    serializer_class = APIPayloadSerializer


class PublicAPIView(BaseAPIView):
    permission_classes = [permissions.AllowAny]


class AuthenticatedAPIView(BaseAPIView):
    permission_classes = [permissions.IsAuthenticated]


class SearchAPIView(PublicAPIView):

    @extend_schema(responses=APIPayloadSerializer)
    def get(self, request):
        serializer = SearchQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data
        qs = filter_products(
            query=data.get("query"),
            price_min=data.get("price_min"),
            price_max=data.get("price_max"),
            category=data.get("category"),
            nearby_only=data.get("nearby_only", False),
            user=request.user,
        )
        return Response(ProductsSerializer(qs[:50], many=True).data)


class RecommendationsAPIView(AuthenticatedAPIView):

    @extend_schema(responses=APIPayloadSerializer)
    def get(self, request):
        recommended_products, user_location = get_recommended_products(request.user)
        return Response(
            {
                "recommended_products": ProductsSerializer(recommended_products, many=True).data,
                "user_location": user_location,
            }
        )

search/views.py
from django.shortcuts import render, get_object_or_404
from foodCreate.models import Category, SubCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, Http404,HttpResponse, JsonResponse

from owner.models import Affiliate
from search.recommendations import get_recommended_products
from search.services import filter_products, is_valid_queryparam


def filter(request):
    order = request.GET.get('order', '')
    view_mode = request.GET.get('view', 'list')
    affiliates = Affiliate.objects.all()[:10]
    # qs = qs.order_by(order)
    categories = Category.objects.all()
    subcategory = SubCategory.objects.all()
    is_favourite = False
    title_contains_query = request.GET.get('title_contains_query')
    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    date_min = request.GET.get('date_min')
    date_max = request.GET.get('date_max')
    category = request.GET.get('category')
    nearby_only = request.GET.get('nearby') == 'on'

    qs = filter_products(
        query=title_contains_query,
        price_min=price_min,
        price_max=price_max,
        category=category,
        nearby_only=nearby_only,
        order=order,
        user=request.user,
    )

    if is_valid_queryparam(date_min):
        qs = qs.filter(created_date__gte=date_min)

    if is_valid_queryparam(date_max):
        qs = qs.filter(created_date__lt=date_max)

    paginator = Paginator(qs, 2)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'queryset': queryset,'categories': categories,'is_favourite': is_favourite,
        'order': order,'page': page,'affiliates':affiliates,'view_mode': view_mode,
        'nearby_only': nearby_only

    }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":
        html = render_to_string("search/results.html", context, request=request)
        return JsonResponse({"html": html, "count": len(queryset)})

    return render(request, "search/main_search.html", context)


def product_recommendations(request):
    recommended_products, user_location = get_recommended_products(request.user)
    return render(
        request,
        "search/recommendations.html",
        {
            "recommended_products": recommended_products,
            "user_location": user_location,
        },
    )

templates/search/ajax_search.html
{% load static %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}


{% for ad in queryset %}
<div class="property-listing property-1">

    <div class="listing-img-wrapper">
        {% for images in ad.get_first_image %}
            {% thumbnail images.ad_image "800x530" crop="10px 10px"  as im %}
                <a href="{{ ad.get_absolute_url }}">
                    <img  style="margin:{{ im|margin:"800x530" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" class="img-fluid mx-auto" alt="" />
                </a>
            {% endthumbnail %}
        {% endfor %}
        <div class="listing-like-top" id = "part{{ ad.id }}">
            {% include 'home/favourite_section.html' %}
        </div>

        <div class="listing-rating">
            <i class="ti-star filled"></i>
            <i class="ti-star filled"></i>
            <i class="ti-star filled"></i>
            <i class="ti-star filled"></i>
            <i class="ti-star"></i>
        </div>
        <span class="property-type">{{ ad.property_offer }}</span>
    </div>

    <div class="listing-content">

        <div class="listing-detail-wrapper">

{#                                        <h6 class="">{{ ad.category }}</h6>#}
            <div class="listing-short-detail">
                <span class="listing-location" style="color: #00A877">{{ ad.category }}</span>
                <h4 class="listing-name"><a href="{{ ad.get_absolute_url }}">{{ ad.property_title }}</a></h4>
                <span class="listing-location"><i class="ti-location-pin"></i>{{ ad.address|truncatechars_html:50 }}</span>
            </div>
            <div class="list-author">
                <a href="#"><img src="{{ ad.profile.photo.url }}" class="img-circle avater-30" alt=""></a>
            </div>
        </div>

        <div class="listing-features-info">
            <ul>
                <li><strong>Bed:</strong>{{ ad.bedroom }}</li>
                <li><strong>Bath:</strong>{{ ad.bathroom }}</li>
                <li><strong>Sqft:</strong>{{ ad.property_area }}</li>
            </ul>
        </div>

        <div class="listing-footer-wrapper">
            <div class="listing-price">
                <h4 class="list-pr">£{{ ad.property_price|intcomma}}</h4>
            </div>
            <div class="listing-detail-btn">
                <a href="{{ ad.get_absolute_url }}" class="more-btn">More Info</a>
            </div>
        </div>

    </div>

</div>
{% empty %}
    <div class="container-fluid">
        <h3 style="text-align:center;">No Property found </h3>
    </div>
{% endfor %}

templates/search/main_search.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}
{% load templatehelpers %}

{% block title %}Your search{% endblock %}

{% block content %}
     <div class="breadcrumb-area mb-50">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="breadcrumb-container">
						<ul>
                            {% if not category %}
                                <li><a href="{% url "home:home" %}"><i class="fa fa-home"></i> Home</a></li>
                                <li class="active">Food List</li>
                            {% else %}
                                <li><a href="{% url "home:home" %}"><i class="fa fa-home"></i> Home</a></li>
                                <li><a href="{% url "home:ads_list" %}">Food List</a></li>
							    <li class="active">{{ category.name }}</li>
                            {% endif %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

    <div class="shop-page-container mb-50">
		<div class="container">
			<div class="row">

                {% include 'search/sub_search.html' %}

				<div class="col-lg-9 order-1 order-lg-2 mb-sm-35 mb-xs-35">

					<!--=======  Shop header  =======-->

					<div class="shop-header mb-35">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 d-flex flex-column flex-sm-row justify-content-between align-items-left align-items-sm-center">
								<!--=======  Sort by dropdown  =======-->

								<div class="form-group mb-0">
                                    <label class="mb-0" for="sort-select">Sort By</label>
                                    <select class="form-control" id="sort-select" name="order">
                                        <option value="latest" {% if order == 'latest' or order == '-created_date' %}selected{% endif %}>Latest Items</option>
                                        <option value="discount_close" {% if order == 'discount_close' %}selected{% endif %}>Discount Ending Soon</option>
                                        <option value="rating" {% if order == 'rating' %}selected{% endif %}>Top Rated</option>
                                        <option value="best_selling" {% if order == 'best_selling' %}selected{% endif %}>Best Selling</option>
                                        <option value="created_date" {% if order == 'created_date' %}selected{% endif %}>Oldest First</option>
                                        <option value="-price" {% if order == '-price' %}selected{% endif %}>High - Low Price</option>
                                        <option value="price" {% if order == 'price' %}selected{% endif %}>Low - High Price</option>
                                    </select>
                                </div>
								<!--=======  End of Sort by dropdown  =======-->
                                <div class="d-flex align-items-center mt-3 mt-sm-0">
                                    <a class="btn btn-outline-success mr-2 js-filter-link {% if view_mode == 'grid' %}active{% endif %}"
                                       href={{ request.build_absolute_uri }}{% relative_url 'grid' 'view' params %}>Grid</a>
                                    <a class="btn btn-outline-success js-filter-link {% if view_mode != 'grid' %}active{% endif %}"
                                       href={{ request.build_absolute_uri }}{% relative_url 'list' 'view' params %}>List</a>
                                </div>
                                {% with total_property=queryset|length %}
								<p class="result-show-message">Showing <span id="search-result-count">{{ total_property }}</span> result{{ total_property|pluralize }}</p>
                                {% endwith %}
							</div>
						</div>
					</div>

					<!--=======  End of Shop header  =======-->

					<!--=======  Grid list view  =======-->

					<div id="search-results">
                        {% include 'search/results.html' %}
                    </div>

					<!--=======  End of Pagination container  =======-->

				</div>
			</div>
		</div>
	</div>
    {% include 'home/affiliate.html' %}
{% endblock %}
{% block script %}
    <script src="{% static 'assets/js/ads.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/search_filters.js' %}" type="text/javascript"></script>
{% endblock %}

templates/search/other_search.html
{% load static %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load thumbnail %}


<div class="header-advance-search modern-search voice-assistant" data-voice-container>
    <form method="GET" action="{% url 'product_search:product_filter' %}">
        <span class="search-icon" aria-hidden="true"><span class="icon_search"></span></span>
        <input type="text" name="title_contains_query" placeholder="Search fresh deals and nearby shops" value="{{ request.GET.title_contains_query.strip }}">
        <button class="voice-assistant__button" type="button" data-voice-action="search" data-voice-input="title_contains_query" aria-label="Start voice search">
            <span class="fa fa-microphone" aria-hidden="true"></span>
        </button>
        <button type="submit">Search</button>
    </form>
    <p class="voice-assistant__status" data-voice-status aria-live="polite"></p>
</div>

templates/search/recommendations.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load thumbnail %}

{% block title %}Recommended for you{% endblock %}

{% block content %}
    <div class="breadcrumb-area mb-50">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="breadcrumb-container">
                        <ul>
                            <li><a href="{% url "home:home" %}"><i class="fa fa-home"></i> Home</a></li>
                            <li class="active">Recommendations</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="shop-page-container mb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shop-header mb-35">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 d-flex flex-column flex-sm-row justify-content-between align-items-left align-items-sm-center">
                                <h3 class="mb-0">Recommended for you</h3>
                                {% if user_location.city or user_location.state %}
                                    <p class="result-show-message mb-0">
                                        Based on your location:
                                        {% if user_location.city %}{{ user_location.city }}{% endif %}
                                        {% if user_location.state %}{% if user_location.city %}, {% endif %}{{ user_location.state }}{% endif %}
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="shop-product-wrap list row no-gutters mb-35">
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
                            {% for ad in recommended_products %}
                                <div class="gf-product shop-list-view-product">
                                    <div class="image">
                                        <a href="{{ ad.get_absolute_url }}">
                                            <span class="{{ ad.get_label_display }}">{{ ad.status }}</span>
                                            {% if ad.delivery %}
                                                <span class="days">Del:{{ ad.delivery }}</span>
                                            {% endif %}
                                            {% for images in ad.get_second_image %}
                                                {% thumbnail images.product_image "306x280" crop="10px 10px" as im %}
                                                    <a href="{{ ad.get_absolute_url }}">
                                                        <img style="margin:{{ im|margin:"306x280" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" alt="" />
                                                    </a>
                                                {% endthumbnail %}
                                            {% endfor %}
                                        </a>
                                    </div>
                                    <div class="product-content">
                                        <div class="product-categories">
                                            <a>{{ ad.category }}</a>
                                        </div>
                                        <h3 class="product-title"><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></h3>
                                        <div class="price-box mb-20">
                                            {% if ad.discount_price %}
                                                <span class="discounted-price">£{{ ad.discount_price|intcomma }}</span>
                                                <span class="main-price">£{{ ad.price|intcomma }}</span>
                                            {% else %}
                                                <span class="discounted-price">£{{ ad.price|intcomma }}</span>
                                            {% endif %}
                                        </div>
                                        <p class="product-description">{{ ad.description }}</p>
                                    </div>
                                </div>
                            {% empty %}
                                <div class="container-fluid">
                                    <h3 style="text-align:center;">No recommendations yet.</h3>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/search/results.html
{% load static %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}
{% load templatehelpers %}

<!--=======  Grid list view  =======-->

<div class="shop-product-wrap {% if view_mode == 'grid' %}grid{% else %}list{% endif %} row no-gutters mb-35">

    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
        {% for ad in queryset %}
            <div class="gf-product shop-list-view-product">
                <div class="image">
                    <a href="{{ ad.get_absolute_url }}">
                        <span class="{{ ad.get_label_display }}">{{ ad.status }}</span>
                        {% if ad.delivery %}
                            <span class="days">Del:{{ ad.delivery }}</span>
                        {% endif %}
                        {% for images in ad.get_second_image %}
                            {% thumbnail images.product_image "306x280" crop="10px 10px"  as im %}
                                <a href="{{ ad.get_absolute_url }}">
                                    <img  style="margin:{{ im|margin:"306x280" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" class="" alt="" />
                                </a>
                            {% endthumbnail %}
                        {% endfor %}
                    </a>
                </div>
                <div class="product-content">
                    <div class="product-categories">
                        <a>{{ ad.category }}</a>
                    </div>
                    <h3 class="product-title"><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></h3>
                    <div class="price-box mb-20">
                         {% if ad.discount_price %}
                          <span class="discounted-price">£{{ ad.discount_price|intcomma}}</span>
                          <span class="main-price">£{{ ad.discount_price|intcomma}}</span>
                         {% else %}
                          <span class="discounted-price">£{{ ad.price|intcomma}}</span>
                        {% endif %}
                    </div>
                    <p class="product-description"> {{ ad.description }}</p>
                    <div class="list-product-icons" id = "part{{ ad.id }}">
                        {% include 'home/special_section.html' %}
                    </div>
                </div>

            </div>
        {% empty %}
            <div class="container-fluid">
                <h3 style="text-align:center;">No search found </h3>
            </div>
        {% endfor %}
        <!--=======  End of Shop list view product  =======-->
    </div>
</div>

<!--=======  End of Grid list view  =======-->

<!--=======  Pagination container  =======-->

<div class="pagination-container">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  pagination-content  =======-->

                <div class="pagination-content text-center">
                    {% if queryset.has_other_pages %}
                      <ul class="">
                        {% if queryset.has_previous %}
                          <li><a class="js-filter-link" href={% relative_url queryset.previous_page_number 'page' request.GET.urlencode %}><i class="fa fa-angle-left"></i></a></li>
                        {% else %}
                          <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}

                        {% if queryset.number|add:'-4' > 1 %}
                            <li><a class="js-filter-link" href={% relative_url queryset.number|add:'-5' 'page' request.GET.urlencode %}>&hellip;</a></li>
                        {% endif %}

                        {% for i in queryset.paginator.page_range %}
                          {% if queryset.number == i %}
                            <li><a class="page-link active"><span>{{ i }}<span class="sr-only">(current)</span></span></a></li>
                          {% elif i > queryset.number|add:'-5' and i < queryset.number|add:'5' %}
                            <li><a class="js-filter-link" href={% relative_url i 'page' request.GET.urlencode %}>{{ i }}</a></li>
                          {% endif %}
                        {% endfor %}

                        {% if queryset.paginator.num_pages > queryset.number|add:'4' %}
                            <li><a class="js-filter-link" href={% relative_url queryset.number|add:'5' 'page' request.GET.urlencode %}>&hellip;</a></li>
                        {% endif %}

                        {% if queryset.has_next %}
                          <li><a class="js-filter-link" href={% relative_url queryset.next_page_number 'page' request.GET.urlencode %}><i class="fa fa-angle-right"></i></a></li>
                        {% else %}
                          <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                      </ul>
                    {% endif %}
                </div>

                <!--=======  End of pagination-content  =======-->
            </div>
        </div>
    </div>
</div>

<!--=======  End of Pagination container  =======-->

templates/search/sub_search.html
{% load static %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load thumbnail %}


<div class="col-lg-3 order-2 order-lg-1">
					<!--=======  sidebar area  =======-->

					<div class="sidebar-area">
                        <form method="GET" action="{% url 'product_search:product_filter' %}" id="search-filter-form">
                            <input type="hidden" name="order" value="{{ request.GET.order.strip }}"/>
                            <input type="hidden" name="view" value="{{ request.GET.view.strip }}"/>
                            <!--=======  single sidebar  =======-->

                            <div class="sidebar mb-35">
                                <h3 class="sidebar-title">Search Products</h3>
                                <div class="sidebar-search">
                                    <input class="form-control {% if request.GET.title_contains_query.strip %}border border-success{% endif %}" type="text" name="title_contains_query"
                                           placeholder="Search by name or description"
                                           value="{{ request.GET.title_contains_query.strip }}">
                                </div>
                            </div>

                            <div class="sidebar mb-35">
                                <h3 class="sidebar-title">PRODUCT CATEGORIES</h3>
                                <div class="row">
                                    {% for category in categories %}
                                    <div class="col-lg-8 col-md-8 col-sm-8">

                                            <input type="radio" id="{{ category.name }}" {% if category.name == request.GET.category.strip %}checked{% endif %} name="category" value="{{ category.name }}">
                                            <label for="{{ category.name }}" class="{% if category.name == request.GET.category.strip %}text-success font-weight-bold{% endif %}">{{ category.name }}</label>

                                    </div>
                                    {% endfor %}
                                </div>
                            </div>

                            <!--=======  End of single sidebar  =======-->

                            <!--=======  single sidebar  =======-->

                            <div class="sidebar mb-35">
                                <h3 class="sidebar-title">Filter By Price</h3>
                                <div class="sidebar-price">
                                    <div id="price-range"></div>
                                    <input type="text" id="price-amount" readonly>
                                </div>
                                <div>
                                    <label for="txtMin"></label>
                                    <input type="hidden" name="price_min" id="txtMin" value="{{ request.GET.price_min.strip }}"/>
                                </div>
                                <div>
                                    <label for="txtMax"></label>
                                    <input type="hidden" name="price_max" id="txtMax" value="{{ request.GET.price_max.strip }}"/>
                                </div>

                            </div>

                            <div class="sidebar mb-35">
                                <h3 class="sidebar-title">Nearby Shops</h3>
                                <label class="{% if nearby_only %}text-success font-weight-bold{% endif %}">
                                    <input type="checkbox" name="nearby" {% if nearby_only %}checked{% endif %}>
                                    Show shops close to me
                                </label>
                            </div>

                            <div class="">
                                <button class="sidebar-title btn btn-success">Search</button>
                            </div>

                        </form>

					</div>

					<!--=======  End of sidebar area  =======-->
				</div>